### ISSUE TITLE
Lỗi phần hiển thị Top hackers 

### ISSUE THREAD

**Issue by redragonvn** [VNSECURITY/bugrank#9]
Phần top hacker thống kê hình bên dưới chỉ có user vjppro1337 (submit 2 bug đều bị mark là spam). Các submit dạng Anonymous không được thống kê và không được xếp hạng. Có thể vẫn hịển thị top các user dạng Anonymous với màu icon hoặc gravatar khác nhau được không? 

![image](https://user-images.githubusercontent.com/10144947/130777888-c0430aac-6ca2-4fa9-8867-91c6448f4d19.png)

**Comment by psucodervn** [comment]
Trước em nhớ làm thử kiểu tách riêng anonymous rồi, nhưng như vậy thì có thể dựa vào đó để tracking được anonymous (hay đại loại thế) anh. Nên sau đó mới gộp chung lại.

**Comment by redragonvn** [comment]
Vậy thì sửa chỉ hiện thằng nào có score đối với program đó > 0 thôi?

**Comment by psucodervn** [comment]
Ok a, vậy cái anonymous vẫn gộp như hiện tại, chỉ update để hiện hacker có score > 0.
cc @ngoctint1lvc
